# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_document_output_chunks import GetDocumentOutputChunks  # noqa: F401,E501
from swagger_server import util


class GetDocumentOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, chunks: List[GetDocumentOutputChunks]=None, id: int=None):  # noqa: E501
        """GetDocumentOutput - a model defined in Swagger

        :param chunks: The chunks of this GetDocumentOutput.  # noqa: E501
        :type chunks: List[GetDocumentOutputChunks]
        :param id: The id of this GetDocumentOutput.  # noqa: E501
        :type id: int
        """
        self.swagger_types = {
            'chunks': List[GetDocumentOutputChunks],
            'id': int
        }

        self.attribute_map = {
            'chunks': 'chunks',
            'id': 'id'
        }
        self._chunks = chunks
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'GetDocumentOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_document_output of this GetDocumentOutput.  # noqa: E501
        :rtype: GetDocumentOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chunks(self) -> List[GetDocumentOutputChunks]:
        """Gets the chunks of this GetDocumentOutput.


        :return: The chunks of this GetDocumentOutput.
        :rtype: List[GetDocumentOutputChunks]
        """
        return self._chunks

    @chunks.setter
    def chunks(self, chunks: List[GetDocumentOutputChunks]):
        """Sets the chunks of this GetDocumentOutput.


        :param chunks: The chunks of this GetDocumentOutput.
        :type chunks: List[GetDocumentOutputChunks]
        """

        self._chunks = chunks

    @property
    def id(self) -> int:
        """Gets the id of this GetDocumentOutput.


        :return: The id of this GetDocumentOutput.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this GetDocumentOutput.


        :param id: The id of this GetDocumentOutput.
        :type id: int
        """

        self._id = id
