# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.search_output_results import SearchOutputResults  # noqa: F401,E501
from swagger_server import util


class SearchOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, results: List[SearchOutputResults]=None, query: str=None, llm: str=None):  # noqa: E501
        """SearchOutput - a model defined in Swagger

        :param results: The results of this SearchOutput.  # noqa: E501
        :type results: List[SearchOutputResults]
        :param query: The query of this SearchOutput.  # noqa: E501
        :type query: str
        :param llm: The llm of this SearchOutput.  # noqa: E501
        :type llm: str
        """
        self.swagger_types = {
            'results': List[SearchOutputResults],
            'query': str,
            'llm': str
        }

        self.attribute_map = {
            'results': 'results',
            'query': 'query',
            'llm': 'llm'
        }
        self._results = results
        self._query = query
        self._llm = llm

    @classmethod
    def from_dict(cls, dikt) -> 'SearchOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The search_output of this SearchOutput.  # noqa: E501
        :rtype: SearchOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def results(self) -> List[SearchOutputResults]:
        """Gets the results of this SearchOutput.


        :return: The results of this SearchOutput.
        :rtype: List[SearchOutputResults]
        """
        return self._results

    @results.setter
    def results(self, results: List[SearchOutputResults]):
        """Sets the results of this SearchOutput.


        :param results: The results of this SearchOutput.
        :type results: List[SearchOutputResults]
        """

        self._results = results

    @property
    def query(self) -> str:
        """Gets the query of this SearchOutput.


        :return: The query of this SearchOutput.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query: str):
        """Sets the query of this SearchOutput.


        :param query: The query of this SearchOutput.
        :type query: str
        """

        self._query = query

    @property
    def llm(self) -> str:
        """Gets the llm of this SearchOutput.


        :return: The llm of this SearchOutput.
        :rtype: str
        """
        return self._llm

    @llm.setter
    def llm(self, llm: str):
        """Sets the llm of this SearchOutput.


        :param llm: The llm of this SearchOutput.
        :type llm: str
        """

        self._llm = llm
